defmodule Locorum.TestData do
  def html(format) do
    case format do
      "wp_short" ->
        """
        <div class="primary-content"><p itemprop="name" class="name">Wendy's</p></div><div class="first" itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"><div><span itemprop="streetAddress">2605 Bouldercrest Rd SE</span></div><div><span itemprop="addressLocality">Atlanta</span>,<span itemprop="addressRegion">GA</span><span itemprop="postalCode">30316</span></div></div>
        """
      "wp_long" ->
        """
        <div class="primary-content"><p itemprop="name" class="name">Wendy's</p></div><div class="first" itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"><div><span itemprop="streetAddress">2605 Bouldercrest Rd SE</span></div><div><span itemprop="addressLocality">Atlanta</span>,<span itemprop="addressRegion">GA</span><span itemprop="postalCode">30316</span></div></div>
        <div class="primary-content"><p itemprop="name" class="name">Wendy's</p></div><div class="first" itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"><div><span itemprop="streetAddress">1313 Mockingbird Ln</span></div><div><span itemprop="addressLocality">Atlanta</span>,<span itemprop="addressRegion">GA</span><span itemprop="postalCode">30312</span></div></div>
        """
      "local_short" ->
        """
        <div class="bucket"><div class="listing bbGray vcard courtesyListing"><div class="listBlockL"><a omn_key="BS1SEO:305:1:1105" onclick="return loc_click(this);" href="http://www.local.com/business/details/yx/atlanta-ga/lucas-group-2138799/" class="txtBlock item orgClick"><h2 class="title fn org"><b>Lucas</b> <b>Group</b></h2></a> <span class="adr fl"><span class='street-address fl'>950 E. Paces Ferry Road NE Suite 2300,&nbsp;</span><span class="locality region fl">Atlanta, GA</span>&nbsp;</span><a omn_key="BS1SEO:305:1:3003" onclick="return loc_click(this);" href="/business/details/yx/map/atlanta-ga/blucasb-bgroupb-2138799/" class="blueLink">map</a> <p class="desc txt11 clear" style="display:block;"> Lucas Group associates are North America’s premier executive recruiters, serving mid-tier to Fortune 500 ... <a style="display: inline" omn_key="BS1SEO:305:1:1114" onclick="return loc_click(this);" href="http://www.local.com/business/details/yx/atlanta-ga/lucas-group-2138799/" class="blueLink">more</a> </p> </div> <div class="fr mT5 tar">
        """
      "local_long" ->
        """
        <div class="bucket"><div class="listing bbGray vcard courtesyListing"><div class="listBlockL"><a omn_key="BS1SEO:305:1:1105" onclick="return loc_click(this);" href="http://www.local.com/business/details/yx/atlanta-ga/lucas-group-2138799/" class="txtBlock item orgClick"><h2 class="title fn org"><b>Lucas</b> <b>Group</b></h2></a> <span class="adr fl"><span class='street-address fl'>950 E. Paces Ferry Road NE Suite 2300,&nbsp;</span><span class="locality region fl">Atlanta, GA</span>&nbsp;</span><a omn_key="BS1SEO:305:1:3003" onclick="return loc_click(this);" href="/business/details/yx/map/atlanta-ga/blucasb-bgroupb-2138799/" class="blueLink">map</a> <p class="desc txt11 clear" style="display:block;"> Lucas Group associates are North America’s premier executive recruiters, serving mid-tier to Fortune 500 ... <a style="display: inline" omn_key="BS1SEO:305:1:1114" onclick="return loc_click(this);" href="http://www.local.com/business/details/yx/atlanta-ga/lucas-group-2138799/" class="blueLink">more</a> </p> </div> <div class="fr mT5 tar">
        <div class="bucket"><div class="listing bbGray vcard courtesyListing"><div class="listBlockL"><a omn_key="BS1SEO:305:1:1105" onclick="return loc_click(this);" href="http://www.local.com/business/details/yx/atlanta-ga/lucas-group-2138799/" class="txtBlock item orgClick"><h2 class="title fn org"><b>Lucas</b> <b>Group</b></h2></a> <span class="adr fl"><span class='street-address fl'>369 Loomis Ave SE</span><span class="locality region fl">Atlanta, GA</span>&nbsp;</span><a omn_key="BS1SEO:305:1:3003" onclick="return loc_click(this);" href="/business/details/yx/map/atlanta-ga/blucasb-bgroupb-2138799/" class="blueLink">map</a> <p class="desc txt11 clear" style="display:block;"> Lucas Group associates are North America’s premier executive recruiters, serving mid-tier to Fortune 500 ... <a style="display: inline" omn_key="BS1SEO:305:1:1114" onclick="return loc_click(this);" href="http://www.local.com/business/details/yx/atlanta-ga/lucas-group-2138799/" class="blueLink">more</a> </p> </div> <div class="fr mT5 tar">
        """
      _ ->
        "Invalid Format"
    end
  end

  def json(format) do
    case format do
      "yahoo" ->
        """
        {"query":{"count":3,"created":"2016-04-17T01:54:32Z","lang":"en-US","results":{"Result":[{"id":"195240549","xmlns":"urn:yahoo:lcl","Title":"Nebo Agency","Address":"1000 Marietta St Nw, Ste 270","City":"Atlanta","State":"GA","Phone":"(404) 885-1201","Latitude":"33.7786","Longitude":"-84.41066","Rating":{"AverageRating":"NaN","TotalRatings":"0","TotalReviews":"0","LastReviewDate":null,"LastReviewIntro":null},"Distance":"2.13","Url":"https://local.yahoo.com/info-195240549-nebo-agency-atlanta","ClickUrl":"https://local.yahoo.com/info-195240549-nebo-agency-atlanta","MapUrl":"https://local.yahoo.com/info-195240549-nebo-agency-atlanta?viewtype=map","BusinessUrl":null,"BusinessClickUrl":null,"Categories":{"Category":[{"id":"96926908","content":"Internet Access Provider"},{"id":"96926913","content":"Web Service"},{"id":"96930848","content":"Advertising Agency"}]}},{"id":"192349709","xmlns":"urn:yahoo:lcl","Title":"Nebo Agency LLC","Address":"1000 Marietta St Nw, #270","City":"Atlanta","State":"GA","Phone":"(404) 885-1201","Latitude":"33.7786","Longitude":"-84.41066","Rating":{"AverageRating":"NaN","TotalRatings":"0","TotalReviews":"0","LastReviewDate":null,"LastReviewIntro":null},"Distance":"2.13","Url":"https://local.yahoo.com/info-192349709-nebo-agency-llc-atlanta","ClickUrl":"https://local.yahoo.com/info-192349709-nebo-agency-llc-atlanta","MapUrl":"https://local.yahoo.com/info-192349709-nebo-agency-llc-atlanta?viewtype=map","BusinessUrl":"http://www.neboagency.com","BusinessClickUrl":"http://www.neboagency.com","Categories":{"Category":[{"id":"96925775","content":"Computer Software"},{"id":"96926913","content":"Web Service"},{"id":"96930848","content":"Advertising Agency"},{"id":"96932690","content":"B2B Computer Retailer"},{"id":"96932693","content":"Computer Communication"},{"id":"96932766","content":"Data Preparation & Processing"},{"id":"96932773","content":"Computer Business Solution"}]}},{"id":"37755281","xmlns":"urn:yahoo:lcl","Title":"Neboweb","Address":"1031 Marietta St Nw","City":"Atlanta","State":"GA","Phone":"(404) 885-1167","Latitude":"33.779615","Longitude":"-84.41123","Rating":{"AverageRating":"NaN","TotalRatings":"0","TotalReviews":"0","LastReviewDate":null,"LastReviewIntro":null},"Distance":"2.07","Url":"https://local.yahoo.com/info-37755281-neboweb-atlanta","ClickUrl":"https://local.yahoo.com/info-37755281-neboweb-atlanta","MapUrl":"https://local.yahoo.com/info-37755281-neboweb-atlanta?viewtype=map","BusinessUrl":"http://www.neboagency.com/","BusinessClickUrl":"http://www.neboagency.com/","Categories":{"Category":[{"id":"96926913","content":"Web Service"},{"id":"96932693","content":"Computer Communication"}]}}]}}}
        """
      _ ->
        "Invalid Format"
    end
  end
end
